- Makefile
- imagebasedupgrade.yaml
This PR adjusts the Makefile to the IBU resource being now [cluster-scoped](https://github.com/openshift-kni/lifecycle-agent/pull/138). It also moves the seed pull secret to the default LCA operator namespace, i.e. `openshift-lifecycle-agent`.
> Remove ibu resource namespace

- .gitignore
- Makefile
- Makefile.ibi
- README.ibi.md
- README.md
- ibi-butane-ignition.yaml
- ibi-manifest.template
- ibi/generate_certs.sh
- ibi/install-rhcos-and-restore-seed.sh
- ibi/ostree-restore.sh
This is a first merge of the work done in https://github.com/javipolo/redhat-pocs/tree/main/ibi/coreos-installer
Second step will be to use same standard tools as in ib-orchestrate-vm (for example, using virsh instead of kcli ...)
> Add Image Based Installation (IBI)

- recert_script.sh
The `:latest` tag of the recert image is not stable, it contains changes
from the `main` branch. We should default to the `:v0` tag instead which
we merge into less often.
> Use recert stable tag

- Makefile
It tries to create nested directories and fail if such don't exist.
> Use recursive mkdir commands

- Makefile
- Remove hardcoded network name
- To guess host IP network has to exist previously, so add a dependency to network target, so we create the network before the VM
> Fix network template changes

- .gitignore
- Makefile
Depends on https://github.com/rh-ecosystem-edge/bip-orchestrate-vm/pull/5 to be merged first
It allows for passing a custom agent-config.yaml file without overwriting the default one in the bip-orchestrate-vm repo
/cc @omertuc 
/cc @eranco74
> Do not overwrite external repo agent-config.yaml

- ostree-var-lib-containers-machineconfig.yaml
This fixes the selinux problems on IBI when using partitioned /var/lib/containers
/cc @eranco74
> MGMT-17283 - Run restorecon on startup

- Makefile
- imagebasedupgrade.yaml
Allow users to set `DISABLE_IBU_ROLLBACK` to `"true"` in order to
disable rollback. This is useful in the CI where we're not interested in
rolling back on failure (as the original cluster has no use for us), but
instead we're more interested in collecting logs from the new failed
stateroot
> New `DISABLE_IBU_ROLLBACK` option

- Makefile
- ostree-var-lib-containers-machineconfig.yaml
- Move some variable definitions after including the .config-override file, so the contents of that file have more priority
- With https://github.com/rh-ecosystem-edge/ib-orchestrate-vm/pull/57 we broke directory-based /var/lib/container sharing. I fixed it, and in the process made it simpler
> Fix and improve /var/lib/container's directory-method and fix variable priority in Makefile

- Makefile.ibi
This way we can streamline the whole IBI flow:
```make ibi-iso ibi-vm-remove ibi-vm ibi-logs ibi-config.iso ibi-attach-config.iso ibi-reboot```
Thanks for coming up with a simple solution for breaking the journalctl command @jeff-roche 
/cc @jeff-roche
> Make ibi-logs exit when the IBI script finished successfully

- Makefile
- imagebasedupgrade.yaml
See https://github.com/openshift-kni/lifecycle-agent/pull/433
Will also fix CI to use the new variable in a separate PR (no need to wait as CI is already broken)
> The API of disabling rollbacks have changed

- imagebasedupgrade.yaml
- seedgenerator.yaml
There is a version upgrade in LCA objects
We need to merge this PR right after https://github.com/openshift-kni/lifecycle-agent/pull/497 is merged into LCA
> Update ImageBasedUpgrade and SeedGenerator objects to apiVersion lca.openshift.io/v1

- Makefile.ibi
This does a few things:
- Adds a single make target for running ibi `make ibi`
- In order to allow that we had to call the parent Makefile's `$(virsh)` which gives sudo and the qemu system target
- Created an IBI_KUBECONFIG env var that allows us to use the parent makefile's `wait-for-install-complete`
- Got rid of any need for the user to call sudo manually
> feat: adding a bunch of things to make running ibi easier (specially for ci)

- Makefile.ibi
- README.ibi.md
This PR adjusts minor IBI readme config ISO name references and the IBI kubeconfig location to the changes adding the IBI config ISO creation via the OCP installer - https://github.com/rh-ecosystem-edge/ib-orchestrate-vm/pull/74.
> Adjust the IBI readme to create config ISO with the OCP installer changes

- Makefile.ibi
This PR extracts the `openshift-install` binary from a release image by default (defined by the `OPENSHIFT_INSTALLER_RELEASE_IMAGE` env var) or directly points to the desired openshift-install binary with the `OPENSHIFT_INSTALLER_BIN` env var, instead of cloning the OCP installer's `master` branch and building it.
Cloning the master branch of the installer and building the openshift-install binary introduced a failure to the IBI CI, because of the following:
- the IBI CI base images use Go 1.21, because LCA requires Go 1.21
- the image-based installer has been added to the OCP installer 4.17 release, which uses Go 1.22
- `GOTOOCHAIN=off` for the base images, which results in the openshift-install build failure as Go is not Go 1.22 and the toolchain won't download and use Go 1.22
In the …
> Extract openshift-install from a release image instead of building it

- oadp-operator.yaml
This PR updates the OADP OLM subscription channel to `stable-1.4`, as `stable-1.3` does not exist in OCP 4.16 anymore and this leads to the seed cluster preparation not succeeding.
```sh
$ oc get clusterversions
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.16.7    True        False         11m     Cluster version is 4.16.7
$ oc get packagemanifests redhat-oadp-operator -oyaml |grep stable-
name: stable-1.0
name: stable-1.1
name: stable-1.2
name: stable-1.4
defaultChannel: stable-1.4
```
> Update oadp stable channel to 1.4 as 1.3 does not exist

- Makefile.ibi
This PR fixes the `ibi-logs` target not terminating because of a change in the log message it's waiting for. :)
> MGMT-17967: fix ibi-logs target not exiting because of changed termination log message

- Makefile.ibi
This change ensures that the `$(OPENSHIFT_INSTALLER_BIN)` `Makefile.ibi` target does not run when the file exists. This way we enforce the priority of the `OPENSHIFT_INSTALLER_BIN` env var over the `OPENSHIFT_INSTALLER_RELEASE_IMAGE` env var.
> MGMT-17967: run openshift-install binary target only if file does not exist

- oadp-operator.yaml
Since a default channel is specified in the package manifest of the OADP operator OLM bundleL
```shell
$ oc get packagemanifests redhat-oadp-operator -oyaml |grep defaultChannel
defaultChannel: stable-1.4
```
we can use it to get the latest stable version of the latter.  This way we won't have to update the `Subscription` whenever a new version comes up or a channel we are currently using suddenly disappears.
/cc @tsorya @javipolo
> Use the defaultChannel for the OADP OLM Subscription

- Makefile.ibi
- README.ibi.md
currently the command extract the binary to:
`bin/openshift-install/openshift-install`  instead of `bin/openshift-install`
> Fix openshift-install target

- recert_script.sh
This PR fixes the recert script not using the correct ingress certificate Common Name, which is `ingress-operator@<timestamp>` and results in recert not signing the ingress certificate with the given key.
> Fix recert not using the proper key to sign the ingress certificate

- Makefile
This PR ensures that operator-sdk is present when deploying LCA via an operator bundle. The proper way would be to add this dependency in the LCA Makefile rule `bundle-run`, but until this change is merged in the LCA repo and all its release branches, I suggest we merge this to fix the broken IBU/IBI CI.
> Ensure operator-sdk is present when deploying LCA from bundle

- Makefile
This change creates the `lifecycle-agent/bin` directory when the operator bundle is used to deploy LCA. The LCA Makefile `operator-sdk` rule assumes that that directory is already present when downloading the `operator-sdk` binary to the latter.
> Create LCA bin dir if not exists

- Makefile.ibi
- image-based-installation-config-template.yaml
Currently when we create configuration in order to write seed image to disk ,
ib-orchestrate provides wrong static networking and we use libvirt dhcp though we want to use static network
> MGMT-19314: we should set valid static network for ibi installation flow
